name: jui_builder
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.4.4
  jsonata: ^0.0.6
  rfc_6901: ^0.2.0
  shared_preferences: ^2.3.2
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  injectable_generator: ^2.6.2

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true