name: jui_builder
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.4.4
  shared_preferences: ^2.3.2
  qr_code_scanner: ^1.0.1
  gap: ^3.0.1
  json_dynamic_widget: ^7.2.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  injectable_generator: ^2.6.2
  json_dynamic_widget_codegen: ^1.0.6+4

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/jsons/
